CREATE OR REPLACE PROCEDURE connexion(ppseudo IN UTILISATEUR.PSEUDO%TYPE,
  ppassword OUT UTILISATEUR.MOT_DE_PASSE%TYPE) IS
  BEGIN
    SELECT MOT_DE_PASSE INTO ppassword FROM UTILISATEUR WHERE PSEUDO=ppseudo;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20002,'Aucun tuple portant ce pseudo !');
  END;