CREATE OR REPLACE FUNCTION connexion(ppseudo IN UTILISATEUR.PSEUDO%TYPE)
  RETURN VARCHAR IS
  vpassword UTILISATEUR.MOT_DE_PASSE%TYPE;
  BEGIN

    SELECT MOT_DE_PASSE INTO vpassword FROM UTILISATEUR WHERE PSEUDO=ppseudo;

    RETURN vpassword;
  END;