
alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS';

CREATE OR REPLACE VIEW highscore_minute AS
   SELECT PSEUDO,DATE_PARTIE,SCORE,NIVEAU
   FROM PARTIE
   WHERE DATE_PARTIE >= (CURRENT_TIMESTAMP - interval '1' minute)
   AND ROWNUM <=5
   ORDER BY SCORE DESC ;

CREATE OR REPLACE VIEW highscore_hour AS
   SELECT PSEUDO,DATE_PARTIE,SCORE,NIVEAU
   FROM PARTIE
   WHERE DATE_PARTIE >= (CURRENT_TIMESTAMP - interval '1' hour)
   AND ROWNUM <=5
   ORDER BY SCORE DESC;

CREATE OR REPLACE VIEW highscore_global AS
   SELECT PSEUDO,DATE_PARTIE,SCORE,NIVEAU
   FROM PARTIE
   WHERE ROWNUM <=5
   ORDER BY SCORE DESC;

