INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);
INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);
INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);
INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);
INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);
INSERT INTO COLLECTION VALUES(SEQ_COLLECTION_ID_COLLECTION.nextval);