INSERT INTO NIVEAU VALUES (1,5,1);
INSERT INTO NIVEAU VALUES (2,8,1);
INSERT INTO NIVEAU VALUES (3,6,2);
INSERT INTO NIVEAU VALUES (4,8,2);
INSERT INTO NIVEAU VALUES (5,6,3);
INSERT INTO NIVEAU VALUES (6,8,3);
INSERT INTO NIVEAU VALUES (7,6,4);
INSERT INTO NIVEAU VALUES (8,8,4);
INSERT INTO NIVEAU VALUES (9,6,5);
INSERT INTO NIVEAU VALUES (10,9,5);

commit;